notifications:
  recipients:
    - gauche-travis@lists.sourceforge.net
language: c
compiler:
  - gcc
  - clang
branches:
  only:
    - master
before_install:
  - curl https://raw.github.com/shirok/Gauche/master/test/setup-travis.sh | sh
before_script:
  - ./DIST gen
